##파일 저장
file=open('test.txt', 'w') #w 쓰기 모드
file.write('test')
file.close()

##파일 읽기
file=open('test.txt', 'r') #r 읽기 모드
whole_str = file.read()
print(whole_str)
file.close()

#try~except를 사용하여 예외 처리
try:
    file=open('test1.txt', 'r')
except FileNotFoundError as fne: #FileNotFoundError -> 예외 발생
                                 #fne -> 예외 메시지를 저장할 변수 
    print('파일을 찾을 수 없습니다. 확인해 주세요')


test='100%'
try:
    number = int(test)
except ValueError:
    print('{}는 숫자가 아닙니다.'.format(test))
    
    
try:
    4/0
except ZeroDivisionError as e: #오류 내용까지 출력
    print(e)
    

#finally사용
file = open('file_not_found_exception', 'w')
try:
    file.read()
except FileNotFoundError as ioe:
    print('파일을 찾을 수 없습니다.') #예외처리
finally:
    file.close() #마지막에 항상 수행
    
#with사용으로 자동으로 파일 닫기(해당 블록이 끝나면 자동으로 꺼짐)
try:
    with open('test.txt') as file:
        print(file.read())
except FileNotFoundError as fne:
    print(fne)

#여러 개의 예외가 발생하는 경우 처리
try:
    a = [1,2]
    print(a[3])
    4/0
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
except IndexError:
    print("인덱싱 할 수 없습니다.")
   
#특정 오류가 발생할 경우 그냥 통과 시켜야 할때
try:
    f = open("ttt.txt", "r")
except FileNotFoundError:
    pass
